### ISSUE TITLE
RSI performance degradation

### ISSUE THREAD

**Issue by lzkill** [bennycode/trading-signals#305]
First of all, thanks for the project! Great work!

When I add the RSI with defaults to my simulations I get a huge performance degradation over time. The RSI update gets slower and slower. Is it expected, am I doing something wrong or is there really a bug hiding in there? 

```typescript
import { Big, BigSource } from 'big.js';
import { BollingerBands, EMA, RSI, SMMA } from 'trading-signals';
import { BandsResult } from 'trading-signals/dist/BANDS/BandsResult';
import { TradeAdvisor } from '../trade-advisor.interface';
import { BaseTradeAdvisor } from '../trade-base-advisor';
import {
  TestBounceAdvisorConfig,
  getMergedConfig,
} from './test-bounce-config';

export class TestBounceAdvisor
  extends BaseTradeAdvisor<BigSource | BandsResult>
  implements TradeAdvisor
{
  private config: TestBounceAdvisorConfig;

  private buyRsi: RSI;
  private buyBands: BollingerBands;
  private buySpreadBands: BollingerBands;
  private sellRsi: RSI;
  private sellBands: BollingerBands;
  private sellSpreadBands: BollingerBands;

  private updateCount = 0;

  constructor(config?: TestBounceAdvisorConfig) {
    super();
    this.config = getMergedConfig(config);
    this.initIndicators();
  }

  private initIndicators() {
    this.initBuyIndicators();
    this.initSellIndicators();
  }

  private initBuyIndicators() {
    this.buyRsi = new RSI(
      this.config.rsi.interval,
      this.config.rsi.indicator === 'ema' ? EMA : SMMA,
    );
    this.buyBands = new BollingerBands(
      this.config.bb.interval,
      this.config.bb.deviationMultiplier,
    );
    this.buySpreadBands = new BollingerBands(
      this.config.bb.interval,
      this.config.bb.deviationMultiplier,
    );
  }

  private initSellIndicators() {
    this.sellRsi = new RSI(
      this.config.rsi.interval,
      this.config.rsi.indicator === 'ema' ? EMA : SMMA,
    );
    this.sellBands = new BollingerBands(
      this.config.bb.interval,
      this.config.bb.deviationMultiplier,
    );
    this.sellSpreadBands = new BollingerBands(
      this.config.bb.interval,
      this.config.bb.deviationMultiplier,
    );
  }

  update(buyPrice: BigSource, sellPrice: BigSource) {
    this.updateIndicators(buyPrice, this.buyRsi, this.buyBands);
    this.updateIndicators(sellPrice, this.sellRsi, this.sellBands);

    if (this.buyBands.isStable && this.sellBands.isStable) {
      this.updateIndicators(this.getSpread(this.buyBands), this.buySpreadBands);
      this.updateIndicators(
        this.getSpread(this.sellBands),
        this.sellSpreadBands,
      );
    }

    // Count all updates as one
    this.updateCount += 1;
  }

  getUpdateCount() {
    return this.updateCount;
  }

  getUpdateCountdown(): number {
    const maxInterval = Math.max(
      this.config.bb.interval,
      this.config.rsi.interval,
    );
    return Math.max(0, maxInterval * 2 - this.updateCount); // spreadBands are updated later
  }

  isCalibrated() {
    return (
      this.buyRsi.isStable &&
      this.buyBands.isStable &&
      this.buySpreadBands.isStable &&
      this.sellRsi.isStable &&
      this.sellBands.isStable &&
      this.sellSpreadBands.isStable
    );
  }

  shouldBuy(price: BigSource) {
    const spread = this.getSpread(this.buyBands);
    return (
      this.isRsiSignalingBuy(this.buyRsi) &&
      this.isBBandsSignalingBuy(this.buyBands, price) &&
      this.isBBandsSpreadStable(this.buySpreadBands, spread)
    );
  }

  shouldSell(price: BigSource) {
    const spread = this.getSpread(this.sellBands);
    return (
      this.isRsiSignalingSell(this.sellRsi) &&
      this.isBBandsSignalingSell(this.sellBands, price) &&
      this.isBBandsSpreadStable(this.sellSpreadBands, spread)
    );
  }

  private isRsiSignalingBuy(rsi: RSI) {
    return rsi.getResult().lt(30);
  }

  private isRsiSignalingSell(rsi: RSI) {
    return rsi.getResult().gt(70);
  }

  private isBBandsSignalingBuy(bbands: BollingerBands, price: BigSource) {
    return bbands.getResult().lower.gte(price);
  }

  private isBBandsSignalingSell(bbands: BollingerBands, price: BigSource) {
    return bbands.getResult().upper.lte(price);
  }

  private isBBandsSpreadStable(spreadBands: BollingerBands, spread: Big) {
    const spreadBandsResult = spreadBands.getResult();
    return (
      spread.gt(spreadBandsResult.lower) && spread.lt(spreadBandsResult.upper)
    );
  }

  private getSpread(bbands: BollingerBands) {
    const result = bbands.getResult();
    return result.upper.minus(result.lower);
  }
}

```

Thanks in advance!

**Comment by bennycode** [comment]
Hi @lzkill and thank you for your report. 👍

After reviewing the RSI implementation, I found out that it uses SMMA by default to calculate the average gain and average loss. Unfortunately, the SMMA was caching all input prices which caused the cache to grow over time which explains your observed performance degradation.

I fixed this behaviour in [this PR](https://github.com/bennycode/trading-signals/pull/307). Please use **trading-signals v2.0.1** to profit from my fix. 

If you like this project, I would be happy if you leave a star: https://github.com/bennycode/trading-signals/stargazers 😀

Best,
Benny

**Comment by lzkill** [comment]
Hi @bennycode, thanks for the reply!

It must be something else, I still see the huge increase in execution time over long simulations. The issue vanishes when I comment out the RSI parts.
